# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu-14.04-amd64-vbox"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  # ansible is not supported on windows, so we bootstrap it in VM and run the playbooks
  require 'rbconfig'
  is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)
  if is_windows
    config.vm.provision "shell" do |sh|
      sh.path = "provisioning/execute-ansible.sh"
      sh.args = "provisioning/oracle-xe.yml provisioning/inventory"
    end
  else
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/apache.yml"
    end
  end

  config.vm.network "forwarded_port", guest: 80, host: 8888, auto_correct: true
end
